services:
  db:
    image: postgres:18
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_DB: ${POSTGRES_DB:-fastapi_backend_template}
      # FORCE Postgres to use the mounted path
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fastapi_backend_template"]
      interval: 3s
      timeout: 3s
      retries: 5

  api:
    build: .
    container_name: fastapi_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment: &api_env
      - PYTHONPATH=/app
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      # Requires a @app.get("/health") route in your FastAPI main.py
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 5s
      timeout: 5s
      retries: 5

  seeder:
    build: .
    container_name: fastapi_seeder
    # Absolute path to the script in the container
    entrypoint: ["/app/scripts/prestart.sh"]
    env_file:
      - .env
    environment: *api_env
    depends_on:
      api:
        condition: service_healthy

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_ui
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data: