[project]
name = "my-fastapi"
version = "0.1.0"
description = "FastAPI learning project"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.135.2",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "pytest-cov>=7.1.0",
]

[tool.pytest.ini_options]
addopts = "--cov=tests --cov-report=term-missing"