"""description of changes

Revision ID: 2f30471845e6
Revises: 92abb142f05f
Create Date: 2026-05-05 20:45:03.465137

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "2f30471845e6"
down_revision: str | Sequence[str] | None = "92abb142f05f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
