"""description of changes

Revision ID: 92abb142f05f
Revises: 2b7f9d8c1a34
Create Date: 2026-05-05 14:13:28.298561

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "92abb142f05f"
down_revision: str | Sequence[str] | None = "2b7f9d8c1a34"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
